
/**
 * Enhancements to Bootstrap components for accessibility.
 *
 * @module     theme_uasdvirtual/myjs
 * @copyright  2018 Damyon Wiese <damyon@moodle.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
require(['jquery'],function($){if($("body").width()>1140){if($('[data-action="toggle-drawer"]').attr('aria-expanded')=='false'){setTimeout(function(){$('[data-action="toggle-drawer"]').click()},2000)}}
topLimit=200;if($("body").attr("id")=="page-grade-report-user-index"){$('.gradeitemheader').removeAttr("href");$('.gradeitemheader').attr("style","display:block !important;color: #1177d1;")}
$(".isStudent .onlyShowDocente").closest("li.activity").remove();$(".isTeacher .onlyShowEstudiante").closest("li.activity").remove();$(".isTeacherEditor .onlyShowEstudiante").closest("li.activity").remove();tkComeBack=$("#page-wrapper").attr("tku");if(!(tkComeBack==undefined)&&tkComeBack.length>0){$('[href="#viewCourses"]').attr("data-key","mycourses");$('[data-key="mycourses"]').append('<form id="comeBackLogin" action="'+$('#loginUASD').val()+'" method="GET"><input type="hidden" name="token" value="'+tkComeBack+'"></form>');$('[data-key="mycourses"]').css("cursor","pointer");$(document).on("click",'[data-key="mycourses"]',function(){$("#comeBackLogin").submit()})}else{$('[href="#viewCourses"]').attr("href",M.cfg.wwwroot+"/my")}
$('.list-group-item[data-type="30"]').each(function(key){href=$(this).attr("href");if(href.indexOf("section=")>0){ind=href.indexOf("section=");href=href.substring(0,ind)+"section="+key}
$(this).attr("href",href);$(this).attr("data-key-section",key)});$('.list-group-item[data-type="30"]').eq(0).addClass("notlist");$('.list-group-item[data-type="30"]').eq(1).addClass("notlist");courseid=$("#page-wrapper").attr("cid");if($("#data-sections-teachers").length>0){sections_teachers=$.parseJSON($("#data-sections-teachers").html());nav=$("#nav-drawer").find(".list-group").first().find("ul");$.each(sections_teachers,function(i,obj){section=$('[data-key-section="'+obj.section+'"]');if(section.length>0){if(obj.visibility==1){section.attr('data-hidden',0)}else{section.attr("data-hidden",1);if($("#page-wrapper").hasClass("isStudent")){section.attr("href","#");section.addClass("linkReturnFalse")}}}else{if(obj.visibility==1){nav.append('<li><a class="list-group-item list-group-item-action " href="'+M.cfg.wwwroot+'/course/view.php?id='+courseid+'&section='+obj.section+'" data-key="2" data-isexpandable="0" data-indent="0" data-showdivider="0" data-type="30" data-nodetype="1" data-collapse="0" data-forceopen="0" data-isactive="0" data-hidden="0" data-preceedwithhr="0" data-parent-key="2" data-key-section="'+obj.section+'"><div class="ml-0"><div class="media"><span class="media-left"><i class="icon fa fa-folder-o fa-fw " aria-hidden="true"></i></span><span class="media-body "></span></div></div></a></li>')}}});function sortList(selector){a=1;$(selector).sort(function(a,b){return(Number(a.getAttribute("data-key-section"))-Number(b.getAttribute("data-key-section")))}).each(function(index,el){$(el).find(".media-body").html("Unidad "+a);$(el).closest("ul").append(el);a++})}
sortList('.list-group-item[data-type="30"]:not(.notlist)')}
if($("body").hasClass("format-uasdvirtual")){if($("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="0"]').length>0){href=$("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="0"]').attr("href");href=href.replace("#section-0","&section=-1");$("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="0"]').attr("href",href)}}
$("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="0"]').find(".media-left").find("i").removeClass("fa-folder-o").addClass("fa-home");$("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="1"]').find(".media-left").find("i").removeClass("fa-folder-o").addClass("fa-book");if($("body").attr("id")=="page-course-view-uasdvirtual"){topLimit=400;$("#nav-drawer").find("nav.list-group:nth-child(2)").find("a.active").find(".media-body").removeClass("font-weight-bold");$("#nav-drawer").find("nav.list-group").find("a.active").removeClass("active");section=$(".single-section ul.uasdvirtual").find("li.section").first();if(!(section.length>0))section=$(".single-section ul.uasdvirtual").find("li.section.hidden").first();if(section.length>0){section=section.attr("id");section=parseInt(section.substring(section.indexOf("-")+1,section.length));$("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="'+section+'"]').addClass("active").find(".media-body").addClass("font-weight-bold")}else{$("#nav-drawer").find("nav.list-group").first().find('a[data-key-section="0"]').addClass("active").find(".media-body").addClass("font-weight-bold")}}
currentScroll=0;margenTopBase=parseInt($("#nav-drawer").css("margin-top"));if(!($(".uasdvirtual_img_course").length>0)){margenTopBase=182}
mySetScroll=setTimeout(setScrollNav(),500);function setScrollNav(isTimer){if(isTimer)sTop="-15px";else{if(currentScroll<window.pageYOffset)sTop=(margenTopBase-window.pageYOffset)+"px";else sTop=(margenTopBase-window.pageYOffset)+"px"}
currentScroll=window.pageYOffset;$("#nav-drawer").css("margin-top",sTop)}
$(document).scroll(function(){clearTimeout(mySetScroll);if(window.pageYOffset>150){if(!($(".navbar.navbar-light").hasClass("fixed-top"))){$(".navbar.navbar-light").addClass("fixed-top");$("body").addClass("is-nav-fixed-top");$(".uasdvirtual_img_course").css("margin-top","50px");$("#page").attr("style","margin-top:65px");$("#nav-drawer > .list-group").first().attr("style","margin-top:45px")}}else{if($(".navbar.navbar-light").hasClass("fixed-top")){$("body").removeClass("is-nav-fixed-top");$(".navbar.navbar-light").removeClass("fixed-top");$(".uasdvirtual_img_course").css("margin-top","");$("#page").removeAttr("style");$("#nav-drawer > .list-group").first().removeAttr("style")}}
if(window.pageYOffset<topLimit){setScrollNav(!1);mySetScroll=setTimeout(setScrollNav(!1),500)}else{setScrollNav(!0);mySetScroll=setTimeout(setScrollNav(!0),500)}});if($("#page-wrapper").hasClass("isTeacher")||$("#page-wrapper").hasClass("isTeacherEditor")){Text=$("#page-wrapper").hasClass("isTeacherEditor")?"Editar disponibilidad":"";iconEditing='<i class="icon fa fa-pencil fa-fw " title="Editar Visibilidad y Fechas" aria-label="Editar Visibilidad y Fechas"></i>';$("#page-course-view-uasdvirtual .header-course .text-full-header .action-menu-trigger .dropdown-menu").prepend('<div class="dropdown-item"><a href="#"  class="setEditingTeacher" role="menuitem">'+iconEditing+' Editar disponibilidad</a></div>')}
$(document).on("click",".setEditingTeacher",function(){if($("body").hasClass("isEditing")){$("body").removeClass("isEditing");$(".change-date-assing").closest("span").remove();$(".change-visibility").remove();text=$("#page-wrapper").hasClass("isTeacherEditor")?"Editar disponibilidad":""
$(this).html(iconEditing+text);$(".change-date-assing").remove();$('.list-group-item[data-type="30"]').each(function(){key=$(this).attr("data-key-section");if(key>1){href=$(this).find(".media").find(".media-body a").attr("href");$(this).attr("href",href);$(this).find(".media").find(".media-body").html($(this).find(".media").find(".media-body a").html())}})}else{$("body").addClass("isEditing")
$(this).html(iconEditing+"Desactivar fechas");$(".content ul.section .modtype_assign").each(function(){$(this).find(".activityinstance").append('<i class="icon fa fa-calendar fa-fw change-date-assing"></i>')});$('.list-group-item[data-type="30"]').each(function(){key=$(this).attr("data-key-section");if(key>1){hidden=$(this).attr("data-hidden")==1?"ishidden":"";href=$(this).attr("href");$(this).find(".media").find(".media-body").html('<a href="'+href+'">'+$(this).find(".media").find(".media-body").html()+'</a>');$(this).find(".media").append('<span class="media-right"><i class="icon fa fa-eye fa-fw '+hidden+' change-visibility" data-key-section="'+key+'"></i></span>');$(this).attr("href","#")}})}
return!1});$(document).on("click",'.linkReturnFalse',function(){return!1});$(document).on("click",".change-visibility",function(){section=$(this).attr("data-key-section");cid=$("#page-wrapper").attr("cid");v=$(this).hasClass("ishidden")?1:0;obj=$(this);$.post(M.cfg.wwwroot+"/wslocal.php",{action:"change_section_visibility",courseid:cid,visibility:v,section:section},function(data){data=$.parseJSON(data);if(data.status==!0){obj.closest('.list-group-item[data-type="30"]').attr("data-hidden",v==1?0:1);if(v==0)obj.addClass("ishidden");else obj.removeClass("ishidden")}});return!1});$(document).on("click",".change-date-assing",function(){cid=$("#page-wrapper").attr("cid");intanceid=$(this).closest("li.activity").attr("id").replace("module-","");instancename=$(this).closest("li.activity").find(".instancename").html();$.post(M.cfg.wwwroot+"/wslocal.php",{action:"change_activity_date",courseid:cid,cmid:intanceid,activity:instancename},function(obj){obj=$.parseJSON(obj);mySetModal(obj.data);$(".my-modals.change_activity_date fieldset > .fcontainer").each(function(){$(this).find("[data-groupname]").each(function(){text=$(this).closest("[data-groupname]").find(".col-md-3 .col-form-label").html();$(this).find(".col-md-3").remove();$(this).find(".col-md-9").addClass("col-sm-12").removeClass("col-md-9");if(!($(this).find(".form-check").find("input").is(":checked"))){$(this).find("select").attr("disabled","disabled")}
input=$(this).find(".form-check").find("input");$(this).find(".form-check").html("").append(input).append(text)})})});return!1});$(document).on("click",".my-modals .collapseexpand",function(){if($(this).hasClass("collapse-all")){$(this).removeClass("collapse-all");$(this).closest("form").find("fieldset:not(#id_availability_)").addClass("collapsed")}else{$(this).addClass("collapse-all");$(this).closest("form").find("fieldset:not(#id_availability_)").removeClass("collapsed")}});$(document).on("click",".my-modals .collapsible legend",function(){if($(this).closest(".collapsible").hasClass("collapsed"))
$(this).closest(".collapsible").removeClass("collapsed");else $(this).closest(".collapsible").addClass("collapsed")});$(document).on("change",".change_activity_date input.form-check-input",function(){if($(this).is(":checked")){$(this).closest("fieldset").find("select").removeAttr("disabled")}else{$(this).closest("fieldset").find("select").attr("disabled","disabled")}});$(document).on("click",".my-modals.change_activity_date .apply-all",function(){modal=$(".my-modals");modal.find(".collapseexpand").addClass("collapse-all");modal.find(".collapseexpand").closest("form").find("fieldset:not(#id_availability_)").removeClass("collapsed");fieldset=$(".my-modals").find("fieldset.collapsible#id_availability_");modal.find("fieldset.collapsible:not(#id_availability_)").each(function(){for(a=0;a<2;a++){i=0;$(this).find("fieldset").eq(a).find("select").each(function(){$(this).val(fieldset.find("fieldset").eq(a).find("select").eq(i).val());if(fieldset.find("fieldset").eq(a).find("select").eq(i).is(":disabled")){$(this).attr("disabled","disabled");$(this).closest("fieldset").find(".form-check-input").prop("checked",!1)}else{$(this).removeAttr("disabled");$(this).closest("fieldset").find(".form-check-input").prop("checked",!0)}
i++})}})});$(document).on("click",".my-modals.change_activity_date .save",function(){date=new Array();cid=$("#page-wrapper").attr("cid");cmid=$(this).attr("cmid");nPosition=["timestart","timeend"];$(this).closest(".my-modals").find("fieldset.collapsible:not(#id_availability_)").each(function(){position=0;groupid=$(this).attr("id").replace("id_availability_","");$(this).find("fieldset").each(function(){if($(this).find("input.form-check-input").is(":checked")){val=new Array();$(this).find("select").each(function(){val.push($(this).val())})
date.push({groupid:groupid,name:nPosition[position],value:val.join("/")})}
position++})});$.post(M.cfg.wwwroot+"/wslocal.php",{action:"change_activity_date",courseid:cid,cmid:cmid,date:JSON.stringify(date),edit:!0},function(obj){obj=$.parseJSON(obj);if(obj.status)closeModal();else alert("Error de Cominicación!")})});$(document).on("click",".my-modals .cancel",function(){closeModal()})});function setMargenModal(){if($('.my-modals').is(":visible")){$('.my-modals').css("margin-left",($(window).width()-500)/2)}}
function closeModal(){if($('.my-modals-bg').is(":visible")){$('.my-modals-bg').remove();$('.my-modals').remove()}}
function mySetModal(data){closeModal();modal='<div class="my-modals-bg"></div><div class="my-modals '+data.class+'"><div class="my-modal-header">'+data.header+'<div class="my-modal-header-close cancel">X</div></div><div class="my-modal-body my-scroll">'+data.content+'</div><div class="my-modal-footer">'+data.footer+'</div></div>';$('body').prepend(modal);setMargenModal()}